-- ============================================================================
-- Utthan National Location Master: Complete 784 Districts Seed
-- Authoritative Source: Local Government Directory (LGD), Ministry of Panchayati Raj, Govt of India
-- Safe to re-run: Uses ON CONFLICT (id) DO UPDATE
-- Covers all 36 States/UTs and exactly 784 official districts
-- ============================================================================

-- The LGD columns are part of the initial schema. Keep these idempotent guards
-- for databases created before Phase 2A made the migration self-contained.
ALTER TABLE states ADD COLUMN IF NOT EXISTS lgd_code INTEGER;
ALTER TABLE districts ADD COLUMN IF NOT EXISTS lgd_district_code INTEGER;

-- Ensure states table has official LGD codes updated
UPDATE states SET lgd_code = 1 WHERE id = 'ut-jk';
UPDATE states SET lgd_code = 2 WHERE id = 'state-hp';
UPDATE states SET lgd_code = 3 WHERE id = 'state-pb';
UPDATE states SET lgd_code = 4 WHERE id = 'ut-ch';
UPDATE states SET lgd_code = 5 WHERE id = 'state-ut';
UPDATE states SET lgd_code = 6 WHERE id = 'state-hr';
UPDATE states SET lgd_code = 7 WHERE id = 'ut-dl';
UPDATE states SET lgd_code = 8 WHERE id = 'state-rj';
UPDATE states SET lgd_code = 9 WHERE id = 'state-up';
UPDATE states SET lgd_code = 10 WHERE id = 'state-br';
UPDATE states SET lgd_code = 11 WHERE id = 'state-sk';
UPDATE states SET lgd_code = 12 WHERE id = 'state-ar';
UPDATE states SET lgd_code = 13 WHERE id = 'state-nl';
UPDATE states SET lgd_code = 14 WHERE id = 'state-mn';
UPDATE states SET lgd_code = 15 WHERE id = 'state-mz';
UPDATE states SET lgd_code = 16 WHERE id = 'state-tr';
UPDATE states SET lgd_code = 17 WHERE id = 'state-ml';
UPDATE states SET lgd_code = 18 WHERE id = 'state-as';
UPDATE states SET lgd_code = 19 WHERE id = 'state-wb';
UPDATE states SET lgd_code = 20 WHERE id = 'state-jh';
UPDATE states SET lgd_code = 21 WHERE id = 'state-od';
UPDATE states SET lgd_code = 22 WHERE id = 'state-ct';
UPDATE states SET lgd_code = 23 WHERE id = 'state-mp';
UPDATE states SET lgd_code = 24 WHERE id = 'state-gj';
UPDATE states SET lgd_code = 27 WHERE id = 'state-mh';
UPDATE states SET lgd_code = 28 WHERE id = 'state-ap';
UPDATE states SET lgd_code = 29 WHERE id = 'state-ka';
UPDATE states SET lgd_code = 30 WHERE id = 'state-ga';
UPDATE states SET lgd_code = 31 WHERE id = 'ut-ld';
UPDATE states SET lgd_code = 32 WHERE id = 'state-kl';
UPDATE states SET lgd_code = 33 WHERE id = 'state-tn';
UPDATE states SET lgd_code = 34 WHERE id = 'ut-py';
UPDATE states SET lgd_code = 35 WHERE id = 'ut-an';
UPDATE states SET lgd_code = 36 WHERE id = 'state-tg';
UPDATE states SET lgd_code = 37 WHERE id = 'ut-la';
UPDATE states SET lgd_code = 38 WHERE id = 'ut-dn';

-- Seed All 784 Districts
INSERT INTO districts (id, state_id, name, code, lgd_district_code) VALUES
('dist-an-nicobars', 'ut-an', 'Nicobars', 'AN-603', 603),
('dist-an-north-and-middle-andaman', 'ut-an', 'North And Middle Andaman', 'AN-632', 632),
('dist-an-south-andamans', 'ut-an', 'South Andamans', 'AN-602', 602),
('dist-ap-alluri-sitharama-raju', 'state-ap', 'Alluri Sitharama Raju', 'AP-745', 745),
('dist-ap-anakapalli', 'state-ap', 'Anakapalli', 'AP-744', 744),
('dist-ap-ananthapuramu', 'state-ap', 'Ananthapuramu', 'AP-502', 502),
('dist-ap-annamayya', 'state-ap', 'Annamayya', 'AP-753', 753),
('dist-ap-bapatla', 'state-ap', 'Bapatla', 'AP-750', 750),
('dist-ap-chittoor', 'state-ap', 'Chittoor', 'AP-503', 503),
('dist-ap-dr-b-r-ambedkar-konaseema', 'state-ap', 'Dr. B.R. Ambedkar Konaseema', 'AP-747', 747),
('dist-ap-east-godavari', 'state-ap', 'East Godavari', 'AP-505', 505),
('dist-ap-eluru', 'state-ap', 'Eluru', 'AP-748', 748),
('dist-ap-guntur', 'state-ap', 'Guntur', 'AP-506', 506),
('dist-ap-kakinada', 'state-ap', 'Kakinada', 'AP-746', 746),
('dist-ap-krishna', 'state-ap', 'Krishna', 'AP-510', 510),
('dist-ap-kurnool', 'state-ap', 'Kurnool', 'AP-511', 511),
('dist-ap-markapuram', 'state-ap', 'Markapuram', 'AP-790', 790),
('dist-ap-nandyal', 'state-ap', 'Nandyal', 'AP-755', 755),
('dist-ap-ntr', 'state-ap', 'Ntr', 'AP-749', 749),
('dist-ap-palnadu', 'state-ap', 'Palnadu', 'AP-751', 751),
('dist-ap-parvathipuram-manyam', 'state-ap', 'Parvathipuram Manyam', 'AP-743', 743),
('dist-ap-polavaram', 'state-ap', 'Polavaram', 'AP-791', 791),
('dist-ap-prakasam', 'state-ap', 'Prakasam', 'AP-517', 517),
('dist-ap-srikakulam', 'state-ap', 'Srikakulam', 'AP-519', 519),
('dist-ap-sri-potti-sriramulu-nellore', 'state-ap', 'Sri Potti Sriramulu Nellore', 'AP-515', 515),
('dist-ap-sri-sathya-sai', 'state-ap', 'Sri Sathya Sai', 'AP-754', 754),
('dist-ap-tirupati', 'state-ap', 'Tirupati', 'AP-752', 752),
('dist-ap-visakhapatnam', 'state-ap', 'Visakhapatnam', 'AP-520', 520),
('dist-ap-vizianagaram', 'state-ap', 'Vizianagaram', 'AP-521', 521),
('dist-ap-west-godavari', 'state-ap', 'West Godavari', 'AP-523', 523),
('dist-ap-y-s-r-kadapa', 'state-ap', 'Y.S.R. Kadapa', 'AP-504', 504),
('dist-ar-anjaw', 'state-ar', 'Anjaw', 'AR-628', 628),
('dist-ar-bichom', 'state-ar', 'Bichom', 'AR-787', 787),
('dist-ar-changlang', 'state-ar', 'Changlang', 'AR-229', 229),
('dist-ar-dibang-valley', 'state-ar', 'Dibang Valley', 'AR-230', 230),
('dist-ar-east-kameng', 'state-ar', 'East Kameng', 'AR-231', 231),
('dist-ar-east-siang', 'state-ar', 'East Siang', 'AR-232', 232),
('dist-ar-kamle', 'state-ar', 'Kamle', 'AR-718', 718),
('dist-ar-keyi-panyor', 'state-ar', 'Keyi Panyor', 'AR-786', 786),
('dist-ar-kra-daadi', 'state-ar', 'Kra Daadi', 'AR-677', 677),
('dist-ar-kurung-kumey', 'state-ar', 'Kurung Kumey', 'AR-233', 233),
('dist-ar-leparada', 'state-ar', 'Leparada', 'AR-724', 724),
('dist-ar-lohit', 'state-ar', 'Lohit', 'AR-234', 234),
('dist-ar-longding', 'state-ar', 'Longding', 'AR-666', 666),
('dist-ar-lower-dibang-valley', 'state-ar', 'Lower Dibang Valley', 'AR-235', 235),
('dist-ar-lower-siang', 'state-ar', 'Lower Siang', 'AR-719', 719),
('dist-ar-lower-subansiri', 'state-ar', 'Lower Subansiri', 'AR-236', 236),
('dist-ar-namsai', 'state-ar', 'Namsai', 'AR-678', 678),
('dist-ar-pakke-kessang', 'state-ar', 'Pakke Kessang', 'AR-723', 723),
('dist-ar-papum-pare', 'state-ar', 'Papum Pare', 'AR-237', 237),
('dist-ar-shi-yomi', 'state-ar', 'Shi Yomi', 'AR-725', 725),
('dist-ar-siang', 'state-ar', 'Siang', 'AR-679', 679),
('dist-ar-tawang', 'state-ar', 'Tawang', 'AR-238', 238),
('dist-ar-tirap', 'state-ar', 'Tirap', 'AR-239', 239),
('dist-ar-upper-siang', 'state-ar', 'Upper Siang', 'AR-240', 240),
('dist-ar-upper-subansiri', 'state-ar', 'Upper Subansiri', 'AR-241', 241),
('dist-ar-west-kameng', 'state-ar', 'West Kameng', 'AR-242', 242),
('dist-ar-west-siang', 'state-ar', 'West Siang', 'AR-243', 243),
('dist-as-bajali', 'state-as', 'Bajali', 'AS-739', 739),
('dist-as-baksa', 'state-as', 'Baksa', 'AS-616', 616),
('dist-as-barpeta', 'state-as', 'Barpeta', 'AS-280', 280),
('dist-as-biswanath', 'state-as', 'Biswanath', 'AS-705', 705),
('dist-as-bongaigaon', 'state-as', 'Bongaigaon', 'AS-281', 281),
('dist-as-cachar', 'state-as', 'Cachar', 'AS-282', 282),
('dist-as-charaideo', 'state-as', 'Charaideo', 'AS-708', 708),
('dist-as-chirang', 'state-as', 'Chirang', 'AS-612', 612),
('dist-as-darrang', 'state-as', 'Darrang', 'AS-283', 283),
('dist-as-dhemaji', 'state-as', 'Dhemaji', 'AS-284', 284),
('dist-as-dhubri', 'state-as', 'Dhubri', 'AS-285', 285),
('dist-as-dibrugarh', 'state-as', 'Dibrugarh', 'AS-DIB', 286),
('dist-as-dima-hasao', 'state-as', 'Dima Hasao', 'AS-299', 299),
('dist-as-goalpara', 'state-as', 'Goalpara', 'AS-287', 287),
('dist-as-golaghat', 'state-as', 'Golaghat', 'AS-288', 288),
('dist-as-hailakandi', 'state-as', 'Hailakandi', 'AS-289', 289),
('dist-as-hojai', 'state-as', 'Hojai', 'AS-709', 709),
('dist-as-jorhat', 'state-as', 'Jorhat', 'AS-290', 290),
('dist-as-kamrup', 'state-as', 'Kamrup', 'AS-291', 291),
('dist-as-kamrup-metro', 'state-as', 'Kamrup Metro', 'AS-KAM', 618),
('dist-as-karbi-anglong', 'state-as', 'Karbi Anglong', 'AS-292', 292),
('dist-as-kokrajhar', 'state-as', 'Kokrajhar', 'AS-294', 294),
('dist-as-lakhimpur', 'state-as', 'Lakhimpur', 'AS-295', 295),
('dist-as-majuli', 'state-as', 'Majuli', 'AS-706', 706),
('dist-as-marigaon', 'state-as', 'Marigaon', 'AS-296', 296),
('dist-as-nagaon', 'state-as', 'Nagaon', 'AS-297', 297),
('dist-as-nalbari', 'state-as', 'Nalbari', 'AS-298', 298),
('dist-as-sivasagar', 'state-as', 'Sivasagar', 'AS-300', 300),
('dist-as-sonitpur', 'state-as', 'Sonitpur', 'AS-301', 301),
('dist-as-south-salmara-mancachar', 'state-as', 'South Salmara Mancachar', 'AS-707', 707),
('dist-as-sribhumi', 'state-as', 'Sribhumi', 'AS-293', 293),
('dist-as-tamulpur', 'state-as', 'Tamulpur', 'AS-756', 756),
('dist-as-tinsukia', 'state-as', 'Tinsukia', 'AS-302', 302),
('dist-as-udalguri', 'state-as', 'Udalguri', 'AS-617', 617),
('dist-as-west-karbi-anglong', 'state-as', 'West Karbi Anglong', 'AS-710', 710),
('dist-br-araria', 'state-br', 'Araria', 'BR-188', 188),
('dist-br-arwal', 'state-br', 'Arwal', 'BR-611', 611),
('dist-br-aurangabad', 'state-br', 'Aurangabad', 'BR-189', 189),
('dist-br-banka', 'state-br', 'Banka', 'BR-190', 190),
('dist-br-begusarai', 'state-br', 'Begusarai', 'BR-191', 191),
('dist-br-bhagalpur', 'state-br', 'Bhagalpur', 'BR-BGP', 192),
('dist-br-bhojpur', 'state-br', 'Bhojpur', 'BR-193', 193),
('dist-br-buxar', 'state-br', 'Buxar', 'BR-194', 194),
('dist-br-darbhanga', 'state-br', 'Darbhanga', 'BR-DBG', 195),
('dist-br-gaya', 'state-br', 'Gaya', 'BR-GAY', 196),
('dist-br-gopalganj', 'state-br', 'Gopalganj', 'BR-197', 197),
('dist-br-jamui', 'state-br', 'Jamui', 'BR-198', 198),
('dist-br-jehanabad', 'state-br', 'Jehanabad', 'BR-199', 199),
('dist-br-kaimur-bhabua', 'state-br', 'Kaimur (Bhabua)', 'BR-200', 200),
('dist-br-katihar', 'state-br', 'Katihar', 'BR-201', 201),
('dist-br-khagaria', 'state-br', 'Khagaria', 'BR-202', 202),
('dist-br-kishanganj', 'state-br', 'Kishanganj', 'BR-203', 203),
('dist-br-lakhisarai', 'state-br', 'Lakhisarai', 'BR-204', 204),
('dist-br-madhepura', 'state-br', 'Madhepura', 'BR-205', 205),
('dist-br-madhubani', 'state-br', 'Madhubani', 'BR-206', 206),
('dist-br-munger', 'state-br', 'Munger', 'BR-207', 207),
('dist-br-muzaffarpur', 'state-br', 'Muzaffarpur', 'BR-MUZ', 208),
('dist-br-nalanda', 'state-br', 'Nalanda', 'BR-NAL', 209),
('dist-br-nawada', 'state-br', 'Nawada', 'BR-210', 210),
('dist-br-pashchim-champaran', 'state-br', 'Pashchim Champaran', 'BR-211', 211),
('dist-br-patna', 'state-br', 'Patna', 'BR-PAT', 212),
('dist-br-purbi-champaran', 'state-br', 'Purbi Champaran', 'BR-213', 213),
('dist-br-purnia', 'state-br', 'Purnia', 'BR-214', 214),
('dist-br-rohtas', 'state-br', 'Rohtas', 'BR-215', 215),
('dist-br-saharsa', 'state-br', 'Saharsa', 'BR-216', 216),
('dist-br-samastipur', 'state-br', 'Samastipur', 'BR-217', 217),
('dist-br-saran', 'state-br', 'Saran', 'BR-218', 218),
('dist-br-sheikhpura', 'state-br', 'Sheikhpura', 'BR-219', 219),
('dist-br-sheohar', 'state-br', 'Sheohar', 'BR-220', 220),
('dist-br-sitamarhi', 'state-br', 'Sitamarhi', 'BR-221', 221),
('dist-br-siwan', 'state-br', 'Siwan', 'BR-222', 222),
('dist-br-supaul', 'state-br', 'Supaul', 'BR-223', 223),
('dist-br-vaishali', 'state-br', 'Vaishali', 'BR-224', 224),
('dist-ch-chandigarh', 'ut-ch', 'Chandigarh', 'CH-44', 44),
('dist-ct-balod', 'state-ct', 'Balod', 'CT-646', 646),
('dist-ct-balodabazar-bhatapara', 'state-ct', 'Balodabazar-Bhatapara', 'CT-644', 644),
('dist-ct-balrampur-ramanujganj', 'state-ct', 'Balrampur-Ramanujganj', 'CT-649', 649),
('dist-ct-bastar', 'state-ct', 'Bastar', 'CT-374', 374),
('dist-ct-bemetara', 'state-ct', 'Bemetara', 'CT-650', 650),
('dist-ct-bijapur', 'state-ct', 'Bijapur', 'CT-636', 636),
('dist-ct-bilaspur', 'state-ct', 'Bilaspur', 'CT-BIL', 375),
('dist-ct-dakshin-bastar-dantewada', 'state-ct', 'Dakshin Bastar Dantewada', 'CT-376', 376),
('dist-ct-dhamtari', 'state-ct', 'Dhamtari', 'CT-377', 377),
('dist-ct-durg', 'state-ct', 'Durg', 'CT-378', 378),
('dist-ct-gariyaband', 'state-ct', 'Gariyaband', 'CT-645', 645),
('dist-ct-gaurela-pendra-marwahi', 'state-ct', 'Gaurela-Pendra-Marwahi', 'CT-734', 734),
('dist-ct-janjgir-champa', 'state-ct', 'Janjgir-Champa', 'CT-379', 379),
('dist-ct-jashpur', 'state-ct', 'Jashpur', 'CT-380', 380),
('dist-ct-kabeerdham', 'state-ct', 'Kabeerdham', 'CT-382', 382),
('dist-ct-khairagarh-chhuikhadan-gandai', 'state-ct', 'Khairagarh-Chhuikhadan-Gandai', 'CT-759', 759),
('dist-ct-kondagaon', 'state-ct', 'Kondagaon', 'CT-643', 643),
('dist-ct-korba', 'state-ct', 'Korba', 'CT-383', 383),
('dist-ct-korea', 'state-ct', 'Korea', 'CT-384', 384),
('dist-ct-mahasamund', 'state-ct', 'Mahasamund', 'CT-385', 385),
('dist-ct-manendragarh-chirmiri-bharatpur-m-c-b', 'state-ct', 'Manendragarh-Chirmiri-Bharatpur(M C B)', 'CT-760', 760),
('dist-ct-mohla-manpur-ambagarh-chouki', 'state-ct', 'Mohla-Manpur-Ambagarh Chouki', 'CT-761', 761),
('dist-ct-mungeli', 'state-ct', 'Mungeli', 'CT-647', 647),
('dist-ct-narayanpur', 'state-ct', 'Narayanpur', 'CT-637', 637),
('dist-ct-raigarh', 'state-ct', 'Raigarh', 'CT-386', 386),
('dist-ct-raipur', 'state-ct', 'Raipur', 'CT-RAI', 387),
('dist-ct-rajnandgaon', 'state-ct', 'Rajnandgaon', 'CT-388', 388),
('dist-ct-sakti', 'state-ct', 'Sakti', 'CT-762', 762),
('dist-ct-sarangarh-bilaigarh', 'state-ct', 'Sarangarh-Bilaigarh', 'CT-763', 763),
('dist-ct-sukma', 'state-ct', 'Sukma', 'CT-642', 642),
('dist-ct-surajpur', 'state-ct', 'Surajpur', 'CT-648', 648),
('dist-ct-surguja', 'state-ct', 'Surguja', 'CT-389', 389),
('dist-ct-uttar-bastar-kanker', 'state-ct', 'Uttar Bastar Kanker', 'CT-381', 381),
('dist-dl-central', 'ut-dl', 'Central', 'DL-77', 77),
('dist-dl-central-north', 'ut-dl', 'Central North', 'DL-796', 796),
('dist-dl-east', 'ut-dl', 'East', 'DL-78', 78),
('dist-dl-new-delhi', 'ut-dl', 'New Delhi', 'DL-79', 79),
('dist-dl-north', 'ut-dl', 'North', 'DL-80', 80),
('dist-dl-north-east', 'ut-dl', 'North East', 'DL-81', 81),
('dist-dl-north-west', 'ut-dl', 'North West', 'DL-82', 82),
('dist-dl-old-delhi', 'ut-dl', 'Old Delhi', 'DL-795', 795),
('dist-dl-outer-north', 'ut-dl', 'Outer North', 'DL-794', 794),
('dist-dl-south', 'ut-dl', 'South', 'DL-83', 83),
('dist-dl-south-east', 'ut-dl', 'South East', 'DL-670', 670),
('dist-dl-south-west', 'ut-dl', 'South West', 'DL-84', 84),
('dist-dl-west', 'ut-dl', 'West', 'DL-85', 85),
('dist-ga-kushavati', 'state-ga', 'Kushavati', 'GA-793', 793),
('dist-ga-north-goa', 'state-ga', 'North Goa', 'GA-551', 551),
('dist-ga-south-goa', 'state-ga', 'South Goa', 'GA-552', 552),
('dist-gj-ahmedabad', 'state-gj', 'Ahmedabad', 'GJ-AHM', 438),
('dist-gj-amreli', 'state-gj', 'Amreli', 'GJ-439', 439),
('dist-gj-anand', 'state-gj', 'Anand', 'GJ-440', 440),
('dist-gj-arvalli', 'state-gj', 'Arvalli', 'GJ-672', 672),
('dist-gj-banas-kantha', 'state-gj', 'Banas Kantha', 'GJ-441', 441),
('dist-gj-bharuch', 'state-gj', 'Bharuch', 'GJ-442', 442),
('dist-gj-bhavnagar', 'state-gj', 'Bhavnagar', 'GJ-443', 443),
('dist-gj-botad', 'state-gj', 'Botad', 'GJ-676', 676),
('dist-gj-chhotaudepur', 'state-gj', 'Chhotaudepur', 'GJ-668', 668),
('dist-gj-dahod', 'state-gj', 'Dahod', 'GJ-445', 445),
('dist-gj-dangs', 'state-gj', 'Dangs', 'GJ-444', 444),
('dist-gj-devbhumi-dwarka', 'state-gj', 'Devbhumi Dwarka', 'GJ-674', 674),
('dist-gj-gandhinagar', 'state-gj', 'Gandhinagar', 'GJ-446', 446),
('dist-gj-gir-somnath', 'state-gj', 'Gir Somnath', 'GJ-675', 675),
('dist-gj-jamnagar', 'state-gj', 'Jamnagar', 'GJ-447', 447),
('dist-gj-junagadh', 'state-gj', 'Junagadh', 'GJ-448', 448),
('dist-gj-kachchh', 'state-gj', 'Kachchh', 'GJ-449', 449),
('dist-gj-kheda', 'state-gj', 'Kheda', 'GJ-450', 450),
('dist-gj-mahesana', 'state-gj', 'Mahesana', 'GJ-451', 451),
('dist-gj-mahisagar', 'state-gj', 'Mahisagar', 'GJ-669', 669),
('dist-gj-morbi', 'state-gj', 'Morbi', 'GJ-673', 673),
('dist-gj-narmada', 'state-gj', 'Narmada', 'GJ-452', 452),
('dist-gj-navsari', 'state-gj', 'Navsari', 'GJ-453', 453),
('dist-gj-panch-mahals', 'state-gj', 'Panch Mahals', 'GJ-454', 454),
('dist-gj-patan', 'state-gj', 'Patan', 'GJ-455', 455),
('dist-gj-porbandar', 'state-gj', 'Porbandar', 'GJ-456', 456),
('dist-gj-rajkot', 'state-gj', 'Rajkot', 'GJ-457', 457),
('dist-gj-sabar-kantha', 'state-gj', 'Sabar Kantha', 'GJ-458', 458),
('dist-gj-surat', 'state-gj', 'Surat', 'GJ-SUR', 459),
('dist-gj-surendranagar', 'state-gj', 'Surendranagar', 'GJ-460', 460),
('dist-gj-tapi', 'state-gj', 'Tapi', 'GJ-641', 641),
('dist-gj-vadodara', 'state-gj', 'Vadodara', 'GJ-VAD', 461),
('dist-gj-valsad', 'state-gj', 'Valsad', 'GJ-462', 462),
('dist-gj-vav-tharad', 'state-gj', 'Vav-Tharad', 'GJ-789', 789),
('dist-hr-ambala', 'state-hr', 'Ambala', 'HR-58', 58),
('dist-hr-bhiwani', 'state-hr', 'Bhiwani', 'HR-59', 59),
('dist-hr-charkhi-dadri', 'state-hr', 'Charkhi Dadri', 'HR-701', 701),
('dist-hr-faridabad', 'state-hr', 'Faridabad', 'HR-FAR', 60),
('dist-hr-fatehabad', 'state-hr', 'Fatehabad', 'HR-61', 61),
('dist-hr-gurugram', 'state-hr', 'Gurugram', 'HR-GUR', 62),
('dist-hr-hansi', 'state-hr', 'Hansi', 'HR-792', 792),
('dist-hr-hisar', 'state-hr', 'Hisar', 'HR-63', 63),
('dist-hr-jhajjar', 'state-hr', 'Jhajjar', 'HR-64', 64),
('dist-hr-jind', 'state-hr', 'Jind', 'HR-65', 65),
('dist-hr-kaithal', 'state-hr', 'Kaithal', 'HR-66', 66),
('dist-hr-karnal', 'state-hr', 'Karnal', 'HR-67', 67),
('dist-hr-kurukshetra', 'state-hr', 'Kurukshetra', 'HR-68', 68),
('dist-hr-mahendragarh', 'state-hr', 'Mahendragarh', 'HR-69', 69),
('dist-hr-nuh', 'state-hr', 'Nuh', 'HR-604', 604),
('dist-hr-palwal', 'state-hr', 'Palwal', 'HR-619', 619),
('dist-hr-panchkula', 'state-hr', 'Panchkula', 'HR-70', 70),
('dist-hr-panipat', 'state-hr', 'Panipat', 'HR-71', 71),
('dist-hr-rewari', 'state-hr', 'Rewari', 'HR-72', 72),
('dist-hr-rohtak', 'state-hr', 'Rohtak', 'HR-73', 73),
('dist-hr-sirsa', 'state-hr', 'Sirsa', 'HR-74', 74),
('dist-hr-sonipat', 'state-hr', 'Sonipat', 'HR-75', 75),
('dist-hr-yamunanagar', 'state-hr', 'Yamunanagar', 'HR-76', 76),
('dist-hp-bilaspur', 'state-hp', 'Bilaspur', 'HP-15', 15),
('dist-hp-chamba', 'state-hp', 'Chamba', 'HP-16', 16),
('dist-hp-hamirpur', 'state-hp', 'Hamirpur', 'HP-17', 17),
('dist-hp-kangra', 'state-hp', 'Kangra', 'HP-18', 18),
('dist-hp-kinnaur', 'state-hp', 'Kinnaur', 'HP-19', 19),
('dist-hp-kullu', 'state-hp', 'Kullu', 'HP-20', 20),
('dist-hp-lahaul-and-spiti', 'state-hp', 'Lahaul And Spiti', 'HP-21', 21),
('dist-hp-mandi', 'state-hp', 'Mandi', 'HP-22', 22),
('dist-hp-shimla', 'state-hp', 'Shimla', 'HP-23', 23),
('dist-hp-sirmaur', 'state-hp', 'Sirmaur', 'HP-24', 24),
('dist-hp-solan', 'state-hp', 'Solan', 'HP-25', 25),
('dist-hp-una', 'state-hp', 'Una', 'HP-26', 26),
('dist-jk-anantnag', 'ut-jk', 'Anantnag', 'JK-1', 1),
('dist-jk-bandipora', 'ut-jk', 'Bandipora', 'JK-623', 623),
('dist-jk-baramulla', 'ut-jk', 'Baramulla', 'JK-3', 3),
('dist-jk-budgam', 'ut-jk', 'Budgam', 'JK-2', 2),
('dist-jk-doda', 'ut-jk', 'Doda', 'JK-4', 4),
('dist-jk-ganderbal', 'ut-jk', 'Ganderbal', 'JK-626', 626),
('dist-jk-jammu', 'ut-jk', 'Jammu', 'JK-JAM', 5),
('dist-jk-kathua', 'ut-jk', 'Kathua', 'JK-7', 7),
('dist-jk-kishtwar', 'ut-jk', 'Kishtwar', 'JK-620', 620),
('dist-jk-kulgam', 'ut-jk', 'Kulgam', 'JK-622', 622),
('dist-jk-kupwara', 'ut-jk', 'Kupwara', 'JK-8', 8),
('dist-jk-poonch', 'ut-jk', 'Poonch', 'JK-10', 10),
('dist-jk-pulwama', 'ut-jk', 'Pulwama', 'JK-11', 11),
('dist-jk-rajouri', 'ut-jk', 'Rajouri', 'JK-12', 12),
('dist-jk-ramban', 'ut-jk', 'Ramban', 'JK-621', 621),
('dist-jk-reasi', 'ut-jk', 'Reasi', 'JK-627', 627),
('dist-jk-samba', 'ut-jk', 'Samba', 'JK-624', 624),
('dist-jk-shopian', 'ut-jk', 'Shopian', 'JK-625', 625),
('dist-jk-srinagar', 'ut-jk', 'Srinagar', 'JK-SRI', 13),
('dist-jk-udhampur', 'ut-jk', 'Udhampur', 'JK-14', 14),
('dist-jh-bokaro', 'state-jh', 'Bokaro', 'JH-322', 322),
('dist-jh-chatra', 'state-jh', 'Chatra', 'JH-323', 323),
('dist-jh-deoghar', 'state-jh', 'Deoghar', 'JH-324', 324),
('dist-jh-dhanbad', 'state-jh', 'Dhanbad', 'JH-325', 325),
('dist-jh-dumka', 'state-jh', 'Dumka', 'JH-326', 326),
('dist-jh-east-singhbhum', 'state-jh', 'East Singhbum', 'JH-ESB', 327),
('dist-jh-garhwa', 'state-jh', 'Garhwa', 'JH-328', 328),
('dist-jh-giridih', 'state-jh', 'Giridih', 'JH-329', 329),
('dist-jh-godda', 'state-jh', 'Godda', 'JH-330', 330),
('dist-jh-gumla', 'state-jh', 'Gumla', 'JH-331', 331),
('dist-jh-hazaribagh', 'state-jh', 'Hazaribagh', 'JH-332', 332),
('dist-jh-jamtara', 'state-jh', 'Jamtara', 'JH-333', 333),
('dist-jh-khunti', 'state-jh', 'Khunti', 'JH-606', 606),
('dist-jh-koderma', 'state-jh', 'Koderma', 'JH-334', 334),
('dist-jh-latehar', 'state-jh', 'Latehar', 'JH-335', 335),
('dist-jh-lohardaga', 'state-jh', 'Lohardaga', 'JH-336', 336),
('dist-jh-pakur', 'state-jh', 'Pakur', 'JH-337', 337),
('dist-jh-palamu', 'state-jh', 'Palamu', 'JH-338', 338),
('dist-jh-ramgarh', 'state-jh', 'Ramgarh', 'JH-607', 607),
('dist-jh-ranchi', 'state-jh', 'Ranchi', 'JH-RAN', 339),
('dist-jh-sahebganj', 'state-jh', 'Sahebganj', 'JH-340', 340),
('dist-jh-saraikela-kharsawan', 'state-jh', 'Saraikela Kharsawan', 'JH-341', 341),
('dist-jh-simdega', 'state-jh', 'Simdega', 'JH-342', 342),
('dist-jh-west-singhbhum', 'state-jh', 'West Singhbhum', 'JH-343', 343),
('dist-ka-bagalkote', 'state-ka', 'Bagalkote', 'KA-524', 524),
('dist-ka-ballari', 'state-ka', 'Ballari', 'KA-528', 528),
('dist-ka-belagavi', 'state-ka', 'Belagavi', 'KA-527', 527),
('dist-ka-bengaluru-rural', 'state-ka', 'Bengaluru Rural', 'KA-526', 526),
('dist-ka-bengaluru-south', 'state-ka', 'Bengaluru South', 'KA-631', 631),
('dist-ka-bengaluru', 'state-ka', 'Bengaluru Urban', 'KA-BLR', 525),
('dist-ka-bidar', 'state-ka', 'Bidar', 'KA-529', 529),
('dist-ka-chamarajanagar', 'state-ka', 'Chamarajanagar', 'KA-531', 531),
('dist-ka-chikkaballapura', 'state-ka', 'Chikkaballapura', 'KA-630', 630),
('dist-ka-chikkamagaluru', 'state-ka', 'Chikkamagaluru', 'KA-532', 532),
('dist-ka-chitradurga', 'state-ka', 'Chitradurga', 'KA-533', 533),
('dist-ka-dakshina-kannada', 'state-ka', 'Dakshina Kannada', 'KA-534', 534),
('dist-ka-davanagere', 'state-ka', 'Davanagere', 'KA-535', 535),
('dist-ka-hubballi', 'state-ka', 'Dharwad', 'KA-DHW', 536),
('dist-ka-gadag', 'state-ka', 'Gadag', 'KA-537', 537),
('dist-ka-hassan', 'state-ka', 'Hassan', 'KA-539', 539),
('dist-ka-haveri', 'state-ka', 'Haveri', 'KA-540', 540),
('dist-ka-kalaburagi', 'state-ka', 'Kalaburagi', 'KA-538', 538),
('dist-ka-kodagu', 'state-ka', 'Kodagu', 'KA-541', 541),
('dist-ka-kolar', 'state-ka', 'Kolar', 'KA-542', 542),
('dist-ka-koppal', 'state-ka', 'Koppal', 'KA-543', 543),
('dist-ka-mandya', 'state-ka', 'Mandya', 'KA-544', 544),
('dist-ka-mysuru', 'state-ka', 'Mysuru', 'KA-MYS', 545),
('dist-ka-raichur', 'state-ka', 'Raichur', 'KA-546', 546),
('dist-ka-shivamogga', 'state-ka', 'Shivamogga', 'KA-547', 547),
('dist-ka-tumakuru', 'state-ka', 'Tumakuru', 'KA-548', 548),
('dist-ka-udupi', 'state-ka', 'Udupi', 'KA-549', 549),
('dist-ka-uttara-kannada', 'state-ka', 'Uttara Kannada', 'KA-550', 550),
('dist-ka-vijayanagara', 'state-ka', 'Vijayanagara', 'KA-738', 738),
('dist-ka-vijayapura', 'state-ka', 'Vijayapura', 'KA-530', 530),
('dist-ka-yadgir', 'state-ka', 'Yadgir', 'KA-635', 635),
('dist-kl-alappuzha', 'state-kl', 'Alappuzha', 'KL-554', 554),
('dist-kl-ernakulam', 'state-kl', 'Ernakulam', 'KL-ERN', 555),
('dist-kl-idukki', 'state-kl', 'Idukki', 'KL-556', 556),
('dist-kl-kannur', 'state-kl', 'Kannur', 'KL-557', 557),
('dist-kl-kasaragod', 'state-kl', 'Kasaragod', 'KL-558', 558),
('dist-kl-kollam', 'state-kl', 'Kollam', 'KL-559', 559),
('dist-kl-kottayam', 'state-kl', 'Kottayam', 'KL-560', 560),
('dist-kl-kozhikode', 'state-kl', 'Kozhikode', 'KL-561', 561),
('dist-kl-malappuram', 'state-kl', 'Malappuram', 'KL-562', 562),
('dist-kl-palakkad', 'state-kl', 'Palakkad', 'KL-563', 563),
('dist-kl-pathanamthitta', 'state-kl', 'Pathanamthitta', 'KL-564', 564),
('dist-kl-thiruvananthapuram', 'state-kl', 'Thiruvananthapuram', 'KL-TVM', 565),
('dist-kl-thrissur', 'state-kl', 'Thrissur', 'KL-566', 566),
('dist-kl-wayanad', 'state-kl', 'Wayanad', 'KL-567', 567),
('dist-la-kargil', 'ut-la', 'Kargil', 'LA-6', 6),
('dist-la-leh-ladakh', 'ut-la', 'Leh Ladakh', 'LA-9', 9),
('dist-ld-lakshadweep-district', 'ut-ld', 'Lakshadweep District', 'LD-553', 553),
('dist-mp-agar-malwa', 'state-mp', 'Agar-Malwa', 'MP-667', 667),
('dist-mp-alirajpur', 'state-mp', 'Alirajpur', 'MP-639', 639),
('dist-mp-anuppur', 'state-mp', 'Anuppur', 'MP-390', 390),
('dist-mp-ashoknagar', 'state-mp', 'Ashoknagar', 'MP-391', 391),
('dist-mp-balaghat', 'state-mp', 'Balaghat', 'MP-392', 392),
('dist-mp-barwani', 'state-mp', 'Barwani', 'MP-393', 393),
('dist-mp-betul', 'state-mp', 'Betul', 'MP-394', 394),
('dist-mp-bhind', 'state-mp', 'Bhind', 'MP-395', 395),
('dist-mp-bhopal', 'state-mp', 'Bhopal', 'MP-BHO', 396),
('dist-mp-burhanpur', 'state-mp', 'Burhanpur', 'MP-397', 397),
('dist-mp-chhatarpur', 'state-mp', 'Chhatarpur', 'MP-398', 398),
('dist-mp-chhindwara', 'state-mp', 'Chhindwara', 'MP-399', 399),
('dist-mp-damoh', 'state-mp', 'Damoh', 'MP-400', 400),
('dist-mp-datia', 'state-mp', 'Datia', 'MP-401', 401),
('dist-mp-dewas', 'state-mp', 'Dewas', 'MP-402', 402),
('dist-mp-dhar', 'state-mp', 'Dhar', 'MP-403', 403),
('dist-mp-dindori', 'state-mp', 'Dindori', 'MP-404', 404),
('dist-mp-guna', 'state-mp', 'Guna', 'MP-406', 406),
('dist-mp-gwalior', 'state-mp', 'Gwalior', 'MP-GWA', 407),
('dist-mp-harda', 'state-mp', 'Harda', 'MP-408', 408),
('dist-mp-indore', 'state-mp', 'Indore', 'MP-IND', 410),
('dist-mp-jabalpur', 'state-mp', 'Jabalpur', 'MP-JAB', 411),
('dist-mp-jhabua', 'state-mp', 'Jhabua', 'MP-412', 412),
('dist-mp-katni', 'state-mp', 'Katni', 'MP-413', 413),
('dist-mp-khandwa-east-nimar', 'state-mp', 'Khandwa (East Nimar)', 'MP-405', 405),
('dist-mp-khargone-west-nimar', 'state-mp', 'Khargone (West Nimar)', 'MP-414', 414),
('dist-mp-maihar', 'state-mp', 'Maihar', 'MP-784', 784),
('dist-mp-mandla', 'state-mp', 'Mandla', 'MP-415', 415),
('dist-mp-mandsaur', 'state-mp', 'Mandsaur', 'MP-416', 416),
('dist-mp-mauganj', 'state-mp', 'MAUGANJ', 'MP-766', 766),
('dist-mp-morena', 'state-mp', 'Morena', 'MP-417', 417),
('dist-mp-narmadapuram', 'state-mp', 'Narmadapuram', 'MP-409', 409),
('dist-mp-narsimhapur', 'state-mp', 'Narsimhapur', 'MP-418', 418),
('dist-mp-neemuch', 'state-mp', 'Neemuch', 'MP-419', 419),
('dist-mp-niwari', 'state-mp', 'Niwari', 'MP-722', 722),
('dist-mp-pandhurna', 'state-mp', 'Pandhurna', 'MP-785', 785),
('dist-mp-panna', 'state-mp', 'Panna', 'MP-420', 420),
('dist-mp-raisen', 'state-mp', 'Raisen', 'MP-421', 421),
('dist-mp-rajgarh', 'state-mp', 'Rajgarh', 'MP-422', 422),
('dist-mp-ratlam', 'state-mp', 'Ratlam', 'MP-423', 423),
('dist-mp-rewa', 'state-mp', 'Rewa', 'MP-424', 424),
('dist-mp-sagar', 'state-mp', 'Sagar', 'MP-425', 425),
('dist-mp-satna', 'state-mp', 'Satna', 'MP-426', 426),
('dist-mp-sehore', 'state-mp', 'Sehore', 'MP-427', 427),
('dist-mp-seoni', 'state-mp', 'Seoni', 'MP-428', 428),
('dist-mp-shahdol', 'state-mp', 'Shahdol', 'MP-429', 429),
('dist-mp-shajapur', 'state-mp', 'Shajapur', 'MP-430', 430),
('dist-mp-sheopur', 'state-mp', 'Sheopur', 'MP-431', 431),
('dist-mp-shivpuri', 'state-mp', 'Shivpuri', 'MP-432', 432),
('dist-mp-sidhi', 'state-mp', 'Sidhi', 'MP-433', 433),
('dist-mp-singrauli', 'state-mp', 'Singrauli', 'MP-638', 638),
('dist-mp-tikamgarh', 'state-mp', 'Tikamgarh', 'MP-434', 434),
('dist-mp-ujjain', 'state-mp', 'Ujjain', 'MP-435', 435),
('dist-mp-umaria', 'state-mp', 'Umaria', 'MP-436', 436),
('dist-mp-vidisha', 'state-mp', 'Vidisha', 'MP-437', 437),
('dist-mh-ahilyanagar', 'state-mh', 'Ahilyanagar', 'MH-466', 466),
('dist-mh-akola', 'state-mh', 'Akola', 'MH-467', 467),
('dist-mh-amravati', 'state-mh', 'Amravati', 'MH-468', 468),
('dist-mh-beed', 'state-mh', 'Beed', 'MH-470', 470),
('dist-mh-bhandara', 'state-mh', 'Bhandara', 'MH-471', 471),
('dist-mh-buldhana', 'state-mh', 'Buldhana', 'MH-472', 472),
('dist-mh-chandrapur', 'state-mh', 'Chandrapur', 'MH-473', 473),
('dist-mh-aurangabad', 'state-mh', 'Chhatrapati Sambhajinagar', 'MH-CSN', 469),
('dist-mh-dharashiv', 'state-mh', 'Dharashiv', 'MH-488', 488),
('dist-mh-dhule', 'state-mh', 'Dhule', 'MH-474', 474),
('dist-mh-gadchiroli', 'state-mh', 'Gadchiroli', 'MH-475', 475),
('dist-mh-gondia', 'state-mh', 'Gondia', 'MH-476', 476),
('dist-mh-hingoli', 'state-mh', 'Hingoli', 'MH-477', 477),
('dist-mh-jalgaon', 'state-mh', 'Jalgaon', 'MH-478', 478),
('dist-mh-jalna', 'state-mh', 'Jalna', 'MH-479', 479),
('dist-mh-kolhapur', 'state-mh', 'Kolhapur', 'MH-480', 480),
('dist-mh-latur', 'state-mh', 'Latur', 'MH-481', 481),
('dist-mh-mumbai', 'state-mh', 'Mumbai', 'MH-482', 482),
('dist-mh-mumbai-suburban', 'state-mh', 'Mumbai Suburban', 'MH-483', 483),
('dist-mh-nagpur', 'state-mh', 'Nagpur', 'MH-NGP', 484),
('dist-mh-nanded', 'state-mh', 'Nanded', 'MH-485', 485),
('dist-mh-nandurbar', 'state-mh', 'Nandurbar', 'MH-486', 486),
('dist-mh-nashik', 'state-mh', 'Nashik', 'MH-NSK', 487),
('dist-mh-palghar', 'state-mh', 'Palghar', 'MH-665', 665),
('dist-mh-parbhani', 'state-mh', 'Parbhani', 'MH-489', 489),
('dist-mh-pune', 'state-mh', 'Pune', 'MH-PUN', 490),
('dist-mh-raigad', 'state-mh', 'Raigad', 'MH-491', 491),
('dist-mh-ratnagiri', 'state-mh', 'Ratnagiri', 'MH-492', 492),
('dist-mh-sangli', 'state-mh', 'Sangli', 'MH-493', 493),
('dist-mh-satara', 'state-mh', 'Satara', 'MH-494', 494),
('dist-mh-sindhudurg', 'state-mh', 'Sindhudurg', 'MH-495', 495),
('dist-mh-solapur', 'state-mh', 'Solapur', 'MH-SOL', 496),
('dist-mh-thane', 'state-mh', 'Thane', 'MH-497', 497),
('dist-mh-wardha', 'state-mh', 'Wardha', 'MH-498', 498),
('dist-mh-washim', 'state-mh', 'Washim', 'MH-499', 499),
('dist-mh-yavatmal', 'state-mh', 'Yavatmal', 'MH-500', 500),
('dist-mn-bishnupur', 'state-mn', 'Bishnupur', 'MN-252', 252),
('dist-mn-chandel', 'state-mn', 'Chandel', 'MN-253', 253),
('dist-mn-churachandpur', 'state-mn', 'Churachandpur', 'MN-254', 254),
('dist-mn-imphal-east', 'state-mn', 'Imphal East', 'MN-255', 255),
('dist-mn-imphal-west', 'state-mn', 'Imphal West', 'MN-256', 256),
('dist-mn-jiribam', 'state-mn', 'Jiribam', 'MN-713', 713),
('dist-mn-kakching', 'state-mn', 'Kakching', 'MN-711', 711),
('dist-mn-kamjong', 'state-mn', 'Kamjong', 'MN-717', 717),
('dist-mn-kangpokpi', 'state-mn', 'Kangpokpi', 'MN-712', 712),
('dist-mn-noney', 'state-mn', 'Noney', 'MN-714', 714),
('dist-mn-pherzawl', 'state-mn', 'Pherzawl', 'MN-715', 715),
('dist-mn-senapati', 'state-mn', 'Senapati', 'MN-257', 257),
('dist-mn-tamenglong', 'state-mn', 'Tamenglong', 'MN-258', 258),
('dist-mn-tengnoupal', 'state-mn', 'Tengnoupal', 'MN-716', 716),
('dist-mn-thoubal', 'state-mn', 'Thoubal', 'MN-259', 259),
('dist-mn-ukhrul', 'state-mn', 'Ukhrul', 'MN-260', 260),
('dist-ml-eastern-west-khasi-hills', 'state-ml', 'Eastern West Khasi Hills', 'ML-740', 740),
('dist-ml-east-garo-hills', 'state-ml', 'East Garo Hills', 'ML-273', 273),
('dist-ml-east-jaintia-hills', 'state-ml', 'East Jaintia Hills', 'ML-657', 657),
('dist-ml-east-khasi-hills', 'state-ml', 'East Khasi Hills', 'ML-274', 274),
('dist-ml-north-garo-hills', 'state-ml', 'North Garo Hills', 'ML-656', 656),
('dist-ml-ri-bhoi', 'state-ml', 'Ri Bhoi', 'ML-276', 276),
('dist-ml-south-garo-hills', 'state-ml', 'South Garo Hills', 'ML-277', 277),
('dist-ml-south-west-garo-hills', 'state-ml', 'South West Garo Hills', 'ML-663', 663),
('dist-ml-south-west-khasi-hills', 'state-ml', 'South West Khasi Hills', 'ML-658', 658),
('dist-ml-west-garo-hills', 'state-ml', 'West Garo Hills', 'ML-278', 278),
('dist-ml-west-jaintia-hills', 'state-ml', 'West Jaintia Hills', 'ML-275', 275),
('dist-ml-west-khasi-hills', 'state-ml', 'West Khasi Hills', 'ML-279', 279),
('dist-mz-aizawl', 'state-mz', 'Aizawl', 'MZ-261', 261),
('dist-mz-champhai', 'state-mz', 'Champhai', 'MZ-262', 262),
('dist-mz-hnahthial', 'state-mz', 'Hnahthial', 'MZ-726', 726),
('dist-mz-khawzawl', 'state-mz', 'Khawzawl', 'MZ-728', 728),
('dist-mz-kolasib', 'state-mz', 'Kolasib', 'MZ-263', 263),
('dist-mz-lawngtlai', 'state-mz', 'Lawngtlai', 'MZ-264', 264),
('dist-mz-lunglei', 'state-mz', 'Lunglei', 'MZ-265', 265),
('dist-mz-mamit', 'state-mz', 'Mamit', 'MZ-266', 266),
('dist-mz-saitual', 'state-mz', 'Saitual', 'MZ-727', 727),
('dist-mz-serchhip', 'state-mz', 'Serchhip', 'MZ-268', 268),
('dist-mz-siaha', 'state-mz', 'Siaha', 'MZ-267', 267),
('dist-nl-chumoukedima', 'state-nl', 'Chumoukedima', 'NL-758', 758),
('dist-nl-dimapur', 'state-nl', 'Dimapur', 'NL-244', 244),
('dist-nl-kiphire', 'state-nl', 'Kiphire', 'NL-614', 614),
('dist-nl-kohima', 'state-nl', 'Kohima', 'NL-245', 245),
('dist-nl-longleng', 'state-nl', 'Longleng', 'NL-615', 615),
('dist-nl-meluri', 'state-nl', 'Meluri', 'NL-788', 788),
('dist-nl-mokokchung', 'state-nl', 'Mokokchung', 'NL-246', 246),
('dist-nl-mon', 'state-nl', 'Mon', 'NL-247', 247),
('dist-nl-niuland', 'state-nl', 'Niuland', 'NL-764', 764),
('dist-nl-noklak', 'state-nl', 'Noklak', 'NL-736', 736),
('dist-nl-peren', 'state-nl', 'Peren', 'NL-613', 613),
('dist-nl-phek', 'state-nl', 'Phek', 'NL-248', 248),
('dist-nl-shamator', 'state-nl', 'Shamator', 'NL-765', 765),
('dist-nl-tseminyu', 'state-nl', 'Tseminyu', 'NL-757', 757),
('dist-nl-tuensang', 'state-nl', 'Tuensang', 'NL-249', 249),
('dist-nl-wokha', 'state-nl', 'Wokha', 'NL-250', 250),
('dist-nl-zunheboto', 'state-nl', 'Zunheboto', 'NL-251', 251),
('dist-od-anugola', 'state-od', 'Anugola', 'OD-344', 344),
('dist-od-balangir', 'state-od', 'Balangir', 'OD-345', 345),
('dist-od-baleshwar', 'state-od', 'Baleshwar', 'OD-346', 346),
('dist-od-baragada', 'state-od', 'Baragada', 'OD-347', 347),
('dist-od-bhadrak', 'state-od', 'Bhadrak', 'OD-348', 348),
('dist-od-boudh', 'state-od', 'Boudh', 'OD-349', 349),
('dist-od-debagada', 'state-od', 'Debagada', 'OD-351', 351),
('dist-od-dhenkanal', 'state-od', 'Dhenkanal', 'OD-352', 352),
('dist-od-gajapati', 'state-od', 'Gajapati', 'OD-353', 353),
('dist-od-ganjam', 'state-od', 'Ganjam', 'OD-354', 354),
('dist-od-jagatsinghapur', 'state-od', 'Jagatsinghapur', 'OD-355', 355),
('dist-od-jajpur', 'state-od', 'Jajpur', 'OD-356', 356),
('dist-od-jharsuguda', 'state-od', 'Jharsuguda', 'OD-357', 357),
('dist-od-kalahandi', 'state-od', 'Kalahandi', 'OD-358', 358),
('dist-od-kandhamala', 'state-od', 'Kandhamala', 'OD-359', 359),
('dist-od-cuttack', 'state-od', 'Kataka', 'OD-CUT', 350),
('dist-od-kendrapada', 'state-od', 'Kendrapada', 'OD-360', 360),
('dist-od-kendujhar', 'state-od', 'Kendujhar', 'OD-361', 361),
('dist-od-khordha', 'state-od', 'Khordha', 'OD-KHO', 362),
('dist-od-koraput', 'state-od', 'Koraput', 'OD-363', 363),
('dist-od-malkangiri', 'state-od', 'Malkangiri', 'OD-364', 364),
('dist-od-mayurbhanj', 'state-od', 'Mayurbhanj', 'OD-365', 365),
('dist-od-nabarangpur', 'state-od', 'Nabarangpur', 'OD-366', 366),
('dist-od-nayagada', 'state-od', 'Nayagada', 'OD-367', 367),
('dist-od-nuapada', 'state-od', 'Nuapada', 'OD-368', 368),
('dist-od-puri', 'state-od', 'Puri', 'OD-PUR', 369),
('dist-od-rayagada', 'state-od', 'Rayagada', 'OD-370', 370),
('dist-od-sambalpur', 'state-od', 'Sambalpur', 'OD-371', 371),
('dist-od-subarnapur', 'state-od', 'Subarnapur', 'OD-372', 372),
('dist-od-sundaragada', 'state-od', 'Sundaragada', 'OD-373', 373),
('dist-py-karaikal', 'ut-py', 'Karaikal', 'PY-598', 598),
('dist-py-puducherry', 'ut-py', 'Puducherry', 'PY-600', 600),
('dist-pb-amritsar', 'state-pb', 'Amritsar', 'PB-ASR', 27),
('dist-pb-barnala', 'state-pb', 'Barnala', 'PB-605', 605),
('dist-pb-bathinda', 'state-pb', 'Bathinda', 'PB-28', 28),
('dist-pb-faridkot', 'state-pb', 'Faridkot', 'PB-29', 29),
('dist-pb-fatehgarh-sahib', 'state-pb', 'Fatehgarh Sahib', 'PB-30', 30),
('dist-pb-fazilka', 'state-pb', 'Fazilka', 'PB-651', 651),
('dist-pb-ferozepur', 'state-pb', 'Ferozepur', 'PB-31', 31),
('dist-pb-gurdaspur', 'state-pb', 'Gurdaspur', 'PB-32', 32),
('dist-pb-hoshiarpur', 'state-pb', 'Hoshiarpur', 'PB-33', 33),
('dist-pb-jalandhar', 'state-pb', 'Jalandhar', 'PB-JAL', 34),
('dist-pb-kapurthala', 'state-pb', 'Kapurthala', 'PB-35', 35),
('dist-pb-ludhiana', 'state-pb', 'Ludhiana', 'PB-LUD', 36),
('dist-pb-malerkotla', 'state-pb', 'Malerkotla', 'PB-737', 737),
('dist-pb-mansa', 'state-pb', 'Mansa', 'PB-37', 37),
('dist-pb-moga', 'state-pb', 'Moga', 'PB-38', 38),
('dist-pb-pathankot', 'state-pb', 'Pathankot', 'PB-662', 662),
('dist-pb-patiala', 'state-pb', 'Patiala', 'PB-41', 41),
('dist-pb-rupnagar', 'state-pb', 'Rupnagar', 'PB-42', 42),
('dist-pb-sangrur', 'state-pb', 'Sangrur', 'PB-43', 43),
('dist-pb-s-a-s-nagar', 'state-pb', 'S.A.S Nagar', 'PB-608', 608),
('dist-pb-shahid-bhagat-singh-nagar', 'state-pb', 'Shahid Bhagat Singh Nagar', 'PB-40', 40),
('dist-pb-sri-muktsar-sahib', 'state-pb', 'Sri Muktsar Sahib', 'PB-39', 39),
('dist-pb-tarn-taran', 'state-pb', 'Tarn Taran', 'PB-609', 609),
('dist-rj-ajmer', 'state-rj', 'Ajmer', 'RJ-86', 86),
('dist-rj-alwar', 'state-rj', 'Alwar', 'RJ-87', 87),
('dist-rj-balotra', 'state-rj', 'Balotra', 'RJ-775', 775),
('dist-rj-banswara', 'state-rj', 'Banswara', 'RJ-88', 88),
('dist-rj-baran', 'state-rj', 'Baran', 'RJ-89', 89),
('dist-rj-barmer', 'state-rj', 'Barmer', 'RJ-90', 90),
('dist-rj-beawar', 'state-rj', 'Beawar', 'RJ-774', 774),
('dist-rj-bharatpur', 'state-rj', 'Bharatpur', 'RJ-91', 91),
('dist-rj-bhilwara', 'state-rj', 'Bhilwara', 'RJ-92', 92),
('dist-rj-bikaner', 'state-rj', 'Bikaner', 'RJ-93', 93),
('dist-rj-bundi', 'state-rj', 'Bundi', 'RJ-94', 94),
('dist-rj-chittorgarh', 'state-rj', 'Chittorgarh', 'RJ-95', 95),
('dist-rj-churu', 'state-rj', 'Churu', 'RJ-96', 96),
('dist-rj-dausa', 'state-rj', 'Dausa', 'RJ-97', 97),
('dist-rj-deeg', 'state-rj', 'Deeg', 'RJ-767', 767),
('dist-rj-dholpur', 'state-rj', 'Dholpur', 'RJ-98', 98),
('dist-rj-didwana-kuchaman', 'state-rj', 'Didwana-Kuchaman', 'RJ-768', 768),
('dist-rj-dungarpur', 'state-rj', 'Dungarpur', 'RJ-99', 99),
('dist-rj-ganganagar', 'state-rj', 'Ganganagar', 'RJ-100', 100),
('dist-rj-hanumangarh', 'state-rj', 'Hanumangarh', 'RJ-101', 101),
('dist-rj-jaipur', 'state-rj', 'Jaipur', 'RJ-JAI', 102),
('dist-rj-jaisalmer', 'state-rj', 'Jaisalmer', 'RJ-103', 103),
('dist-rj-jalore', 'state-rj', 'Jalore', 'RJ-104', 104),
('dist-rj-jhalawar', 'state-rj', 'Jhalawar', 'RJ-105', 105),
('dist-rj-jhunjhunu', 'state-rj', 'Jhunjhunu', 'RJ-106', 106),
('dist-rj-jodhpur', 'state-rj', 'Jodhpur', 'RJ-JOD', 107),
('dist-rj-karauli', 'state-rj', 'Karauli', 'RJ-108', 108),
('dist-rj-khairthal-tijara', 'state-rj', 'Khairthal-Tijara', 'RJ-770', 770),
('dist-rj-kota', 'state-rj', 'Kota', 'RJ-KOT', 109),
('dist-rj-kotputli-behror', 'state-rj', 'Kotputli-Behror', 'RJ-782', 782),
('dist-rj-nagaur', 'state-rj', 'Nagaur', 'RJ-110', 110),
('dist-rj-pali', 'state-rj', 'Pali', 'RJ-111', 111),
('dist-rj-phalodi', 'state-rj', 'Phalodi', 'RJ-772', 772),
('dist-rj-pratapgarh', 'state-rj', 'Pratapgarh', 'RJ-629', 629),
('dist-rj-rajsamand', 'state-rj', 'Rajsamand', 'RJ-112', 112),
('dist-rj-salumbar', 'state-rj', 'Salumbar', 'RJ-777', 777),
('dist-rj-sawai-madhopur', 'state-rj', 'Sawai Madhopur', 'RJ-113', 113),
('dist-rj-sikar', 'state-rj', 'Sikar', 'RJ-114', 114),
('dist-rj-sirohi', 'state-rj', 'Sirohi', 'RJ-115', 115),
('dist-rj-tonk', 'state-rj', 'Tonk', 'RJ-116', 116),
('dist-rj-udaipur', 'state-rj', 'Udaipur', 'RJ-UDA', 117),
('dist-sk-gangtok', 'state-sk', 'Gangtok', 'SK-225', 225),
('dist-sk-gyalshing', 'state-sk', 'Gyalshing', 'SK-228', 228),
('dist-sk-mangan', 'state-sk', 'Mangan', 'SK-226', 226),
('dist-sk-namchi', 'state-sk', 'Namchi', 'SK-227', 227),
('dist-sk-pakyong', 'state-sk', 'Pakyong', 'SK-741', 741),
('dist-sk-soreng', 'state-sk', 'Soreng', 'SK-742', 742),
('dist-tn-ariyalur', 'state-tn', 'Ariyalur', 'TN-610', 610),
('dist-tn-chengalpattu', 'state-tn', 'Chengalpattu', 'TN-730', 730),
('dist-tn-chennai', 'state-tn', 'Chennai', 'TN-CHE', 568),
('dist-tn-coimbatore', 'state-tn', 'Coimbatore', 'TN-CBE', 569),
('dist-tn-cuddalore', 'state-tn', 'Cuddalore', 'TN-570', 570),
('dist-tn-dharmapuri', 'state-tn', 'Dharmapuri', 'TN-571', 571),
('dist-tn-dindigul', 'state-tn', 'Dindigul', 'TN-572', 572),
('dist-tn-erode', 'state-tn', 'Erode', 'TN-573', 573),
('dist-tn-kallakurichi', 'state-tn', 'Kallakurichi', 'TN-729', 729),
('dist-tn-kancheepuram', 'state-tn', 'Kancheepuram', 'TN-574', 574),
('dist-tn-kanniyakumari', 'state-tn', 'Kanniyakumari', 'TN-575', 575),
('dist-tn-karur', 'state-tn', 'Karur', 'TN-576', 576),
('dist-tn-krishnagiri', 'state-tn', 'Krishnagiri', 'TN-577', 577),
('dist-tn-madurai', 'state-tn', 'Madurai', 'TN-MDU', 578),
('dist-tn-mayiladuthurai', 'state-tn', 'Mayiladuthurai', 'TN-735', 735),
('dist-tn-nagapattinam', 'state-tn', 'Nagapattinam', 'TN-579', 579),
('dist-tn-namakkal', 'state-tn', 'Namakkal', 'TN-580', 580),
('dist-tn-perambalur', 'state-tn', 'Perambalur', 'TN-581', 581),
('dist-tn-pudukkottai', 'state-tn', 'Pudukkottai', 'TN-582', 582),
('dist-tn-ramanathapuram', 'state-tn', 'Ramanathapuram', 'TN-583', 583),
('dist-tn-ranipet', 'state-tn', 'Ranipet', 'TN-731', 731),
('dist-tn-salem', 'state-tn', 'Salem', 'TN-SLM', 584),
('dist-tn-sivaganga', 'state-tn', 'Sivaganga', 'TN-585', 585),
('dist-tn-tenkasi', 'state-tn', 'Tenkasi', 'TN-733', 733),
('dist-tn-thanjavur', 'state-tn', 'Thanjavur', 'TN-586', 586),
('dist-tn-theni', 'state-tn', 'Theni', 'TN-588', 588),
('dist-tn-the-nilgiris', 'state-tn', 'The Nilgiris', 'TN-587', 587),
('dist-tn-thiruvallur', 'state-tn', 'Thiruvallur', 'TN-589', 589),
('dist-tn-thiruvarur', 'state-tn', 'Thiruvarur', 'TN-590', 590),
('dist-tn-thoothukkudi', 'state-tn', 'Thoothukkudi', 'TN-594', 594),
('dist-tn-tiruchirappalli', 'state-tn', 'Tiruchirappalli', 'TN-TRI', 591),
('dist-tn-tirunelveli', 'state-tn', 'Tirunelveli', 'TN-592', 592),
('dist-tn-tirupathur', 'state-tn', 'Tirupathur', 'TN-732', 732),
('dist-tn-tiruppur', 'state-tn', 'Tiruppur', 'TN-634', 634),
('dist-tn-tiruvannamalai', 'state-tn', 'Tiruvannamalai', 'TN-593', 593),
('dist-tn-vellore', 'state-tn', 'Vellore', 'TN-595', 595),
('dist-tn-viluppuram', 'state-tn', 'Viluppuram', 'TN-596', 596),
('dist-tn-virudhunagar', 'state-tn', 'Virudhunagar', 'TN-597', 597),
('dist-tg-adilabad', 'state-tg', 'Adilabad', 'TG-501', 501),
('dist-tg-bhadradri-kothagudem', 'state-tg', 'Bhadradri Kothagudem', 'TG-690', 690),
('dist-tg-hanumakonda', 'state-tg', 'Hanumakonda', 'TG-686', 686),
('dist-tg-hyderabad', 'state-tg', 'Hyderabad', 'TG-HYD', 507),
('dist-tg-jagitial', 'state-tg', 'Jagitial', 'TG-681', 681),
('dist-tg-jangoan', 'state-tg', 'Jangoan', 'TG-689', 689),
('dist-tg-jayashankar-bhupalapally', 'state-tg', 'Jayashankar Bhupalapally', 'TG-687', 687),
('dist-tg-jogulamba-gadwal', 'state-tg', 'Jogulamba Gadwal', 'TG-695', 695),
('dist-tg-kamareddy', 'state-tg', 'Kamareddy', 'TG-685', 685),
('dist-tg-karimnagar', 'state-tg', 'Karimnagar', 'TG-508', 508),
('dist-tg-khammam', 'state-tg', 'Khammam', 'TG-509', 509),
('dist-tg-kumuram-bheem-asifabad', 'state-tg', 'Kumuram Bheem Asifabad', 'TG-699', 699),
('dist-tg-mahabubabad', 'state-tg', 'Mahabubabad', 'TG-688', 688),
('dist-tg-mahabubnagar', 'state-tg', 'Mahabubnagar', 'TG-512', 512),
('dist-tg-mancherial', 'state-tg', 'Mancherial', 'TG-684', 684),
('dist-tg-medak', 'state-tg', 'Medak', 'TG-513', 513),
('dist-tg-medchal-malkajgiri', 'state-tg', 'Medchal Malkajgiri', 'TG-700', 700),
('dist-tg-mulugu', 'state-tg', 'Mulugu', 'TG-720', 720),
('dist-tg-nagarkurnool', 'state-tg', 'Nagarkurnool', 'TG-694', 694),
('dist-tg-nalgonda', 'state-tg', 'Nalgonda', 'TG-514', 514),
('dist-tg-narayanpet', 'state-tg', 'Narayanpet', 'TG-721', 721),
('dist-tg-nirmal', 'state-tg', 'Nirmal', 'TG-680', 680),
('dist-tg-nizamabad', 'state-tg', 'Nizamabad', 'TG-516', 516),
('dist-tg-peddapalli', 'state-tg', 'Peddapalli', 'TG-682', 682),
('dist-tg-rajanna-sircilla', 'state-tg', 'Rajanna Sircilla', 'TG-683', 683),
('dist-tg-ranga-reddy', 'state-tg', 'Ranga Reddy', 'TG-518', 518),
('dist-tg-sangareddy', 'state-tg', 'Sangareddy', 'TG-691', 691),
('dist-tg-siddipet', 'state-tg', 'Siddipet', 'TG-692', 692),
('dist-tg-suryapet', 'state-tg', 'Suryapet', 'TG-696', 696),
('dist-tg-vikarabad', 'state-tg', 'Vikarabad', 'TG-698', 698),
('dist-tg-wanaparthy', 'state-tg', 'Wanaparthy', 'TG-693', 693),
('dist-tg-warangal', 'state-tg', 'Warangal', 'TG-WAR', 522),
('dist-tg-yadadri-bhuvanagiri', 'state-tg', 'Yadadri Bhuvanagiri', 'TG-697', 697),
('dist-dn-dadra-and-nagar-haveli', 'ut-dn', 'Dadra And Nagar Haveli', 'DN-465', 465),
('dist-dn-daman', 'ut-dn', 'Daman', 'DN-463', 463),
('dist-dn-diu', 'ut-dn', 'Diu', 'DN-464', 464),
('dist-tr-dhalai', 'state-tr', 'Dhalai', 'TR-269', 269),
('dist-tr-gomati', 'state-tr', 'Gomati', 'TR-654', 654),
('dist-tr-khowai', 'state-tr', 'Khowai', 'TR-652', 652),
('dist-tr-north-tripura', 'state-tr', 'North Tripura', 'TR-270', 270),
('dist-tr-sepahijala', 'state-tr', 'Sepahijala', 'TR-653', 653),
('dist-tr-south-tripura', 'state-tr', 'South Tripura', 'TR-271', 271),
('dist-tr-unakoti', 'state-tr', 'Unakoti', 'TR-655', 655),
('dist-tr-west-tripura', 'state-tr', 'West Tripura', 'TR-272', 272),
('dist-ut-almora', 'state-ut', 'Almora', 'UT-45', 45),
('dist-ut-bageshwar', 'state-ut', 'Bageshwar', 'UT-46', 46),
('dist-ut-chamoli', 'state-ut', 'Chamoli', 'UT-47', 47),
('dist-ut-champawat', 'state-ut', 'Champawat', 'UT-48', 48),
('dist-ut-dehradun', 'state-ut', 'Dehradun', 'UT-DDN', 49),
('dist-ut-haridwar', 'state-ut', 'Haridwar', 'UT-HAR', 50),
('dist-ut-nainital', 'state-ut', 'Nainital', 'UT-51', 51),
('dist-ut-pauri-garhwal', 'state-ut', 'Pauri Garhwal', 'UT-52', 52),
('dist-ut-pithoragarh', 'state-ut', 'Pithoragarh', 'UT-53', 53),
('dist-ut-rudraprayag', 'state-ut', 'Rudraprayag', 'UT-54', 54),
('dist-ut-tehri-garhwal', 'state-ut', 'Tehri Garhwal', 'UT-55', 55),
('dist-ut-udham-singh-nagar', 'state-ut', 'Udham Singh Nagar', 'UT-56', 56),
('dist-ut-uttarkashi', 'state-ut', 'Uttarkashi', 'UT-57', 57),
('dist-up-agra', 'state-up', 'Agra', 'UP-AGR', 118),
('dist-up-aligarh', 'state-up', 'Aligarh', 'UP-ALI', 119),
('dist-up-ambedkar-nagar', 'state-up', 'Ambedkar Nagar', 'UP-121', 121),
('dist-up-amethi', 'state-up', 'Amethi', 'UP-640', 640),
('dist-up-amroha', 'state-up', 'Amroha', 'UP-154', 154),
('dist-up-auraiya', 'state-up', 'Auraiya', 'UP-122', 122),
('dist-up-ayodhya', 'state-up', 'Ayodhya', 'UP-AYO', 140),
('dist-up-azamgarh', 'state-up', 'Azamgarh', 'UP-123', 123),
('dist-up-baghpat', 'state-up', 'Baghpat', 'UP-124', 124),
('dist-up-bahraich', 'state-up', 'Bahraich', 'UP-125', 125),
('dist-up-ballia', 'state-up', 'Ballia', 'UP-126', 126),
('dist-up-balrampur', 'state-up', 'Balrampur', 'UP-127', 127),
('dist-up-banda', 'state-up', 'Banda', 'UP-128', 128),
('dist-up-bara-banki', 'state-up', 'Bara Banki', 'UP-129', 129),
('dist-up-bareilly', 'state-up', 'Bareilly', 'UP-BLY', 130),
('dist-up-basti', 'state-up', 'Basti', 'UP-131', 131),
('dist-up-bhadohi', 'state-up', 'Bhadohi', 'UP-179', 179),
('dist-up-bijnor', 'state-up', 'Bijnor', 'UP-132', 132),
('dist-up-budaun', 'state-up', 'Budaun', 'UP-133', 133),
('dist-up-bulandshahr', 'state-up', 'Bulandshahr', 'UP-134', 134),
('dist-up-chandauli', 'state-up', 'Chandauli', 'UP-135', 135),
('dist-up-chitrakoot', 'state-up', 'Chitrakoot', 'UP-136', 136),
('dist-up-deoria', 'state-up', 'Deoria', 'UP-137', 137),
('dist-up-etah', 'state-up', 'Etah', 'UP-138', 138),
('dist-up-etawah', 'state-up', 'Etawah', 'UP-139', 139),
('dist-up-farrukhabad', 'state-up', 'Farrukhabad', 'UP-141', 141),
('dist-up-fatehpur', 'state-up', 'Fatehpur', 'UP-142', 142),
('dist-up-firozabad', 'state-up', 'Firozabad', 'UP-143', 143),
('dist-up-gautam-buddha-nagar', 'state-up', 'Gautam Buddha Nagar', 'UP-144', 144),
('dist-up-ghaziabad', 'state-up', 'Ghaziabad', 'UP-145', 145),
('dist-up-ghazipur', 'state-up', 'Ghazipur', 'UP-146', 146),
('dist-up-gonda', 'state-up', 'Gonda', 'UP-147', 147),
('dist-up-gorakhpur', 'state-up', 'Gorakhpur', 'UP-GKP', 148),
('dist-up-hamirpur', 'state-up', 'Hamirpur', 'UP-149', 149),
('dist-up-hapur', 'state-up', 'Hapur', 'UP-661', 661),
('dist-up-hardoi', 'state-up', 'Hardoi', 'UP-150', 150),
('dist-up-hathras', 'state-up', 'Hathras', 'UP-163', 163),
('dist-up-jalaun', 'state-up', 'Jalaun', 'UP-151', 151),
('dist-up-jaunpur', 'state-up', 'Jaunpur', 'UP-152', 152),
('dist-up-jhansi', 'state-up', 'Jhansi', 'UP-153', 153),
('dist-up-kannauj', 'state-up', 'Kannauj', 'UP-155', 155),
('dist-up-kanpur-dehat', 'state-up', 'Kanpur Dehat', 'UP-156', 156),
('dist-up-kanpur', 'state-up', 'Kanpur Nagar', 'UP-KNP', 157),
('dist-up-kasganj', 'state-up', 'Kasganj', 'UP-633', 633),
('dist-up-kaushambi', 'state-up', 'Kaushambi', 'UP-158', 158),
('dist-up-kheri', 'state-up', 'Kheri', 'UP-159', 159),
('dist-up-kushinagar', 'state-up', 'Kushinagar', 'UP-160', 160),
('dist-up-lalitpur', 'state-up', 'Lalitpur', 'UP-161', 161),
('dist-up-lucknow', 'state-up', 'Lucknow', 'UP-LKO', 162),
('dist-up-mahoba', 'state-up', 'Mahoba', 'UP-165', 165),
('dist-up-mahrajganj', 'state-up', 'Mahrajganj', 'UP-164', 164),
('dist-up-mainpuri', 'state-up', 'Mainpuri', 'UP-166', 166),
('dist-up-mathura', 'state-up', 'Mathura', 'UP-167', 167),
('dist-up-mau', 'state-up', 'Mau', 'UP-168', 168),
('dist-up-meerut', 'state-up', 'Meerut', 'UP-169', 169),
('dist-up-mirzapur', 'state-up', 'Mirzapur', 'UP-MZP', 170),
('dist-up-moradabad', 'state-up', 'Moradabad', 'UP-171', 171),
('dist-up-muzaffarnagar', 'state-up', 'Muzaffarnagar', 'UP-172', 172),
('dist-up-pilibhit', 'state-up', 'Pilibhit', 'UP-173', 173),
('dist-up-pratapgarh', 'state-up', 'Pratapgarh', 'UP-174', 174),
('dist-up-prayagraj', 'state-up', 'Prayagraj', 'UP-PRY', 120),
('dist-up-rae-bareli', 'state-up', 'Rae Bareli', 'UP-175', 175),
('dist-up-rampur', 'state-up', 'Rampur', 'UP-176', 176),
('dist-up-saharanpur', 'state-up', 'Saharanpur', 'UP-177', 177),
('dist-up-sambhal', 'state-up', 'Sambhal', 'UP-659', 659),
('dist-up-sant-kabir-nagar', 'state-up', 'Sant Kabir Nagar', 'UP-178', 178),
('dist-up-shahjahanpur', 'state-up', 'Shahjahanpur', 'UP-180', 180),
('dist-up-shamli', 'state-up', 'Shamli', 'UP-660', 660),
('dist-up-shrawasti', 'state-up', 'Shrawasti', 'UP-181', 181),
('dist-up-siddharthnagar', 'state-up', 'Siddharthnagar', 'UP-182', 182),
('dist-up-sitapur', 'state-up', 'Sitapur', 'UP-183', 183),
('dist-up-sonbhadra', 'state-up', 'Sonbhadra', 'UP-184', 184),
('dist-up-sultanpur', 'state-up', 'Sultanpur', 'UP-185', 185),
('dist-up-unnao', 'state-up', 'Unnao', 'UP-186', 186),
('dist-up-varanasi', 'state-up', 'Varanasi', 'UP-VAR', 187),
('dist-wb-alipurduar', 'state-wb', 'Alipurduar', 'WB-664', 664),
('dist-wb-bankura', 'state-wb', 'Bankura', 'WB-BNK', 305),
('dist-wb-birbhum', 'state-wb', 'Birbhum', 'WB-BRB', 307),
('dist-wb-cooch-behar', 'state-wb', 'Cooch Behar', 'WB-308', 308),
('dist-wb-dakshin-dinajpur', 'state-wb', 'Dakshin Dinajpur', 'WB-310', 310),
('dist-wb-darjeeling', 'state-wb', 'Darjeeling', 'WB-DAR', 309),
('dist-wb-hooghly', 'state-wb', 'Hooghly', 'WB-312', 312),
('dist-wb-howrah', 'state-wb', 'Howrah', 'WB-HWH', 313),
('dist-wb-jalpaiguri', 'state-wb', 'Jalpaiguri', 'WB-314', 314),
('dist-wb-jhargram', 'state-wb', 'Jhargram', 'WB-703', 703),
('dist-wb-kalimpong', 'state-wb', 'Kalimpong', 'WB-702', 702),
('dist-wb-kolkata', 'state-wb', 'Kolkata', 'WB-KOL', 315),
('dist-wb-malda', 'state-wb', 'Malda', 'WB-316', 316),
('dist-wb-murshidabad', 'state-wb', 'Murshidabad', 'WB-MSD', 319),
('dist-wb-nadia', 'state-wb', 'Nadia', 'WB-NAD', 320),
('dist-wb-n24pgs', 'state-wb', 'North 24 Parganas', 'WB-N24', 303),
('dist-wb-paschim-bardhaman', 'state-wb', 'Paschim Bardhaman', 'WB-704', 704),
('dist-wb-paschim-medinipur', 'state-wb', 'Paschim Medinipur', 'WB-318', 318),
('dist-wb-purba-bardhaman', 'state-wb', 'Purba Bardhaman', 'WB-306', 306),
('dist-wb-purba-medinipur', 'state-wb', 'Purba Medinipur', 'WB-317', 317),
('dist-wb-purulia', 'state-wb', 'Purulia', 'WB-321', 321),
('dist-wb-s24pgs', 'state-wb', 'South 24 Parganas', 'WB-S24', 304),
('dist-wb-uttar-dinajpur', 'state-wb', 'Uttar Dinajpur', 'WB-311', 311)
ON CONFLICT (id) DO UPDATE SET
    state_id = EXCLUDED.state_id,
    name = EXCLUDED.name,
    code = EXCLUDED.code,
    lgd_district_code = EXCLUDED.lgd_district_code;
